spring.application.name=LearnPilot
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://barathash77_db_user:N51iKCTt2PMxcaHr@cluster0.mhew8wh.mongodb.net/learnpilot?appName=Cluster0}
spring.data.mongodb.auto-index-creation=true

server.port=${PORT:8080}
spring.web.cors.allowed-origins=*
grok.api.key=${GROQ_API_KEY}
 