spring.application.name=LearnPilot
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/learnpilot}
spring.data.mongodb.auto-index-creation=true

server.port=${PORT:8080}
spring.web.cors.allowed-origins=*
grok.api.key=${GROQ_API_KEY}
 